=pod 

=encoding utf8

=head1 NOME

Boas práticas

=head1 SINOPSE

Me ajudem a escrever a estrutura das boas práticas, por favor.

=head2 Escreva Perl Moderno

=head2 Use uma framework moderna (catalyst,mojolicious,dancer)

=head2 Use um sistema de controle de versões (git)

=head2 Faça a coisa mais simples que possa funcionar

=head2 Use testes para ver se sua idéia funciona

=head2 Disponibilize o código fonte com uma licença livre

=head2 Participe da comunidade (listas de discussão, irc)

=head1 AUTORES

Solli Honorio
Nelson Ferraz

=cut

